config/routes.rb
Rails.application.routes.draw do
  resources :employees
	root 'public#main'
	get 'public/items'
	get 'public/contacts'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
	validates :first_name, presence:true
	validates :last_name, presence:true
	validates :email, length: {minimum: 5, maximum:20}
def self.search(search)
  if search
    Employee.where('first_name LIKE :search', search: "%#{search}%")
  else
   	Employee.all
 end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :index, only: [:search]
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.search(params[:search])
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :email, :phone)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
  end
  def items
  end
  def contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="d-grid gap-3">
  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone number" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
</div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee list</h1>

<%= form_tag employees_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table class="table table-dark table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.phone %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> 
<%= link_to 'New Employee', new_employee_path,class:"btn btn-secondary" %>

app/views/employees/new.html.erb
<h1>Add new Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4"><%= @employee.first_name %> <%= @employee.last_name %></h1>
    <p class="lead">Email: <%= @employee.email %>, Phone: <%= @employee.phone %></p>
    <body class="text-center">
    <%= link_to 'Edit', edit_employee_path(@employee), class:"btn btn-secondary" %>
	<%= link_to 'Back', employees_path,class:"btn btn-secondary" %>
	</body>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="container">
	<p>&copy; Trying new stuff</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <style>
      hr { 
        display: block;
        margin-top: 0.5em;
        margin-bottom: 0.5em;
        margin-left: auto;
        margin-right: auto;
        border-style: inset;
        border-width: 1px;
        } 
    </style>
  </head>

  <body>
    <header>
      <%= render "layouts/nav/public" %>
    </header>

    <%= yield %>
    <hr>
    <%= render "layouts/footer" %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand">
      <%= link_to "WEBAPP", root_path , class:"navbar-brand"%>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to "Forum", public_items_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Contacts", public_contacts_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Data", employees_path, class:"nav-link"%>
        </li>
      </ul>
    </div>
  </div>
</nav>